module.exports = [
  'Normal',
  'Superscript',
  'Subscript',
  'Monospace',
  'Blackletter',
  'Blackletter Bold',
  'Serif Italic',
  'Serif Bold Italic',
  'Sans Serif',
  'Sans Serif Italic',
  'Sans Serif Bold',
  'Sans Serif Bold Italic',
  'Spongebob',
];
